# Generated by Django 4.1.1 on 2022-10-02 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0006_alter_ads_options_alter_categories_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
